development:
  adapter: postgresql
  encoding: unicode
  database: Recipe_development
  username: dev1
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: Recipe_test
  username: dev1
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: Recipe_production
  username: dev1
  password: